ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "accountStatus" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "DriverProfile" ADD COLUMN IF NOT EXISTS "accountStatus" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "baseFee" DOUBLE PRECISION DEFAULT 350;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "pricePerKm" DOUBLE PRECISION DEFAULT 12;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "sameDaySurchargePct" DOUBLE PRECISION DEFAULT 25;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "expressSurchargePct" DOUBLE PRECISION DEFAULT 45;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "vehicleRatesJson" TEXT;
