ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "serviceType" TEXT NOT NULL DEFAULT 'FREIGHT';
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "shuttleTripType" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "shuttleVehicleClass" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "airportCode" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "flightNumber" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "passengerCount" INTEGER DEFAULT 1;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "luggagePieces" INTEGER;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "hireHours" DOUBLE PRECISION;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "passengerNotes" TEXT;

ALTER TABLE "DriverProfile" ADD COLUMN IF NOT EXISTS "offersFreight" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "DriverProfile" ADD COLUMN IF NOT EXISTS "offersShuttle" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "DriverProfile" ADD COLUMN IF NOT EXISTS "pdpLicenceNumber" TEXT;
ALTER TABLE "Booking" ALTER COLUMN "cargoDescription" DROP NOT NULL;
