ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "cargoSize" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "cargoDimensions" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "cargoImageUrl" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "urgency" TEXT NOT NULL DEFAULT 'STANDARD';
